### ISSUE TITLE
Update redux dependency to use built-in redux typings?

### ISSUE THREAD

**Issue by CarsonF** [asvetliakov/typings-redux-form#2]
The redux package now includes built in [types](https://github.com/reactjs/redux/blob/master/index.d.ts). This is causing some conflict errors (as there are some incompatibilities). Could this package be rewired to use those typings?

**Comment by asvetliakov** [comment]
Hello,
You probably will be fine by using original DT version of redux-form if you want to use original redux typings, my changes to original DT version were very small and since the redux provides own typings now i'll probably going to drop this package since there is no need in it.

**Comment by CarsonF** [comment]
Wouldn't that be a step backwards?

**Comment by asvetliakov** [comment]
I don't think so. TS 2.0 will introduce own solution for management typings and they will be based from DT versions/DT registry

**Comment by CarsonF** [comment]
Isn't that what typings is as well?

**Comment by asvetliakov** [comment]
Typings is different story. TS will use NPM resolving method, typings does that by inlining dependencies into resulting file (i don't like that). Although as i know typings will work with new TS typings management by placing local typings.

**Comment by CarsonF** [comment]
Is there any info for that? All I can find is a line in their Roadmap:

> - tsd integration in tsserver/language service API

**Comment by asvetliakov** [comment]
https://github.com/Microsoft/TypeScript/issues/7156 third comment
Also you can check label "typings" in their issues list
https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+typings+label%3ATypings

**Comment by CarsonF** [comment]
So the version of redux-form on DT doesn't use the redux definition that redux provides. It's still the old one.

**Comment by asvetliakov** [comment]
Yes, it linked to the old redux typings. But in TS 2.0 typings resolution (it will replace ///reference path to ///reference types also) the bundled definition from redux will have precedence over DT version even if `@types/redux` package will be installed as dependency. I don't use redux-form now but you can try byself how it works with typescript@next version.

**Comment by CarsonF** [comment]
I'm not too concerned with how the definition is pulled in. But I guess I'm just lost on how that makes a difference since the definitions are incompatible with each other. 

DT:

``` ts
interface Dispatch extends Function {
    (action: any): any;
}
```

Redux:

``` ts
export interface Dispatch<S> {
    <A extends Action>(action: A): A;
}
```
